[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
# 禁用 mixed-case-function 警告
lint.ignore = ["mixed-case-function"]

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
